name: test-publish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Action
      run: ./action/publish/
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
